name: pull request from release to master
on:
  schedule: [{cron: "* 21 * * *"}]
jobs:
  masterPromotion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with: 
            pr_title: Branch Sync - Weekly Updated from Release to Master
            destination_branch: main
            source_branch: release
            github_token: ${{ secrets.GITHUB_TOKEN}}
            pr_reviewer: GoudSagar
