name: pull request from release to master
on:
  push:
    branches:
      - main
jobs:
  masterPromotion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: GoudSagar/pull-request@v2
        with: 
            pr_title: Branch Sync - Weekly Update from Release to Master
            base: main
            destination_branch: main
            source_branch: release
